"""Write the reproducible experiment report (markdown + JSON) from a real ExperimentResult."""
from __future__ import annotations

import json
from pathlib import Path


def write_report(result, md_path, json_path) -> None:
    s = result.summary
    runs = result.runs
    test_sku = runs[(runs.split == "test") & (runs.level == "sku")].sort_values("mape")
    val_sku = runs[(runs.split == "val") & (runs.level == "sku")].set_index("model")["wape"]
    imp_sku = (s["baseline_mape_sku"] - s["best_mape_sku"]) / s["baseline_mape_sku"] * 100
    imp_tot = (s["baseline_mape_total"] - s["best_mape_total"]) / s["baseline_mape_total"] * 100

    lines = [
        "# Experiment report",
        "",
        "Generated by `python -m retailsense.pipeline.run_experiments`. Every number below is measured, not hand-entered.",
        "",
        "## Protocol",
        f"- Task: one-week-ahead demand per SKU, {s['n_skus']} SKUs, {s['n_features']} features, rolling origin.",
        f"- Split: train -> validation ({s['n_val_weeks']} weeks) -> untouched holdout ({s['n_test_weeks']} weeks, {s['test_start']} to {s['test_end']}).",
        f"- Model selection: {s['selection_rule']}.",
        "- MAPE is computed over rows with actual demand > 0; WAPE (sum abs error / sum actual) is shown too.",
        f"- Configurations compared: {s['n_configs']} fitted models + {s['n_baselines']} naive baselines.",
        "",
        "## Headline (holdout)",
        "",
        "| Level | Best baseline | Baseline MAPE | Best model | Model MAPE | Relative improvement |",
        "|---|---|---|---|---|---|",
        f"| SKU-week | {s['baseline_model']} | {s['baseline_mape_sku']:.1f}% | {s['best_model']} | {s['best_mape_sku']:.1f}% | {imp_sku:.0f}% |",
        f"| Total weekly demand | {s['baseline_model']} | {s['baseline_mape_total']:.1f}% | {s['best_model']} | {s['best_mape_total']:.1f}% | {imp_tot:.0f}% |",
        "",
        f"SKU-level WAPE: baseline {s['baseline_wape_sku']:.1f}% -> model {s['best_wape_sku']:.1f}%.",
        "",
        "## All configurations (SKU level; the selection metric is validation WAPE)",
        "",
        "| Model | Family | Validation WAPE | Holdout MAPE | Holdout WAPE |",
        "|---|---|---|---|---|",
    ]
    for _, r in test_sku.iterrows():
        mark = " (selected)" if r["model"] == s["best_model"] else ""
        lines.append(f"| {r['model']}{mark} | {r['family']} | {val_sku[r['model']]:.1f}% | {r['mape']:.1f}% | {r['wape']:.1f}% |")
    Path(md_path).parent.mkdir(parents=True, exist_ok=True)
    Path(md_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    Path(json_path).write_text(json.dumps(s, indent=2), encoding="utf-8")
